.include <src.opts.mk>

SRCS=	cheriostest.c

SRCS+=	cheriostest_bounds_globals.c					\
	cheriostest_util.c \
	cheriostest_util_vm.c						\
	cheriostest_bounds_globals_x.c					\
	cheriostest_bounds_heap.c					\
	cheriostest_bounds_stack.c					\
	cheriostest_cidcap.c						\
	cheriostest_context.c						\
	cheriostest_fault.c	\
	cheriostest_flag_captured.c					\
	cheriostest_fs.c						\
	cheriostest_ifunc.c						\
	cheriostest_kbounce.c						\
	cheriostest_internal.c 					\
	cheriostest_ipc.c				\
	cheriostest_local_global.c					\
	cheriostest_longjmp.c						\
	cheriostest_printf.c						\
	cheriostest_ptrace.c			\
	cheriostest_registers.c		\
	cheriostest_sealcap.c			\
	cheriostest_signal.c						\
	cheriostest_string.c						\
	cheriostest_tls.c							\
	cheriostest_syscall.c						\
	cheriostest_vm.c						\
	cheriostest_strfcap.c

.if ${MACHINE_ABI:Mpurecap}
SRCS+=	cheriostest_bounds_subobject.c			\
	cheriostest_malloc.c						\
	cheriostest_bounds_varargs.c				\
		cheriostest_sentries.c

.if ${.MAKE.OS} == "FreeBSD"
.if ${MK_COMPARTMENT_POLICY} != "no"
SRCS+=	cheriostest_compartments.c
CFLAGS.cheriostest_compartments.c+=-ffunction-sections
COMPARTMENT_POLICY=	${CHERIOSTEST_DIR}/compartments.json
.endif
.elif ${.MAKE.OS} == "Linux"
# We add this file on Linux regardless of the value of MK_COMPARTMENT_POLICY
# to report this test as an expected failure because compartmentalisation
# is not supported on Linux.
SRCS+=	cheriostest_compartments.c
.endif
.endif

# We currently don't have zlib available on Linux
.if ${.MAKE.OS} == "FreeBSD"
SRCS+=	cheriostest_zlib.c
.endif

CHERIOSTEST_DIR:=	${.PARSEDIR}
.PATH: ${CHERIOSTEST_DIR}
CFLAGS+=	-I${CHERIOSTEST_DIR}/${MACHINE}

CFLAGS+=	'-DPROG="${PROG}"' '-DPROG_SUFFIX="${PROG:S/^cheriostest//}"'

.if ${MACHINE_ABI:Mpurecap}
SRCS+=	cheriostest_cheriabi.c
SRCS+=	cheriostest_cheriabi_libc.c
SRCS+=	cheriostest_cheriabi_open.c
.endif

.if ${.MAKE.OS} == "Linux"
# Include these tests on Linux to report revocation is missing.
CFLAGS+=	-DCHERIOSTEST_CHERI_REVOKE_TESTS
.elif ${MACHINE_ABI:Mpurecap} && ${MK_CHERI_CAPREVOKE} == "yes"
LIBADD+=	cheri_caprevoke
CFLAGS+=	-DCHERIOSTEST_CHERI_REVOKE_TESTS
.endif

# This test is broken as written
#SRCS+=	cheriostest_vm_swap.c
#CFLAGS.cheriostest_vm_swap.c+=-Wno-cheri-capability-misuse

.sinclude "${CHERIOSTEST_DIR}/${MACHINE}/Makefile.cheriostest"

# Enable sub-object bounds only in tests specifically designed for them.
CFLAGS.cheriostest_bounds_subobject.c+=-cheri-bounds=subobject-safe

MAN=

LIBADD+=	util xo
.if ${.MAKE.OS} == "Linux"
# Linux requires libbsd for compatibility
# reasons.
LIBADD+=	bsd
.elif ${.MAKE.OS} == "FreeBSD"
# Linux doesn't have libprocstat and
# libz is currently not available either
LIBADD+=	procstat z
.endif

.ifdef CHERIBSD_DYNAMIC_TESTS
CFLAGS+=	-DCHERIBSD_DYNAMIC_TESTS
CFLAGS+=	'-DLIBM_SONAME="libm.so.5"'
CFLAGS+=	-I${.CURDIR}/../libcheriostest_dynamic
LDFLAGS+=	-L${.OBJDIR}/../libcheriostest_dynamic/
DPADD+=	${.OBJDIR}/../libcheriostest_dynamic/libcheriostest_dynamic.so

.if ${.MAKE.OS} == "Linux"
# On Linux, we are putting the helper libraries in /opt/cheri-os-test/lib to
# avoid polluting system library search paths.
LDFLAGS+= -Wl,-rpath=/opt/cheri-os-test/lib/
.endif
LDADD+=	-Wl,--push-state,-Bdynamic -lcheriostest_dynamic -Wl,--pop-state

SRCS+=	cheriostest_fptr_canon.c \
		cheriostest_lazy_bind.c
.else
NO_SHARED?=	YES
.endif

# Both variants exist so we can test with and without libthr's interposition on
# things like signals.
.ifdef CHERIBSD_THREAD_TESTS
CFLAGS+=	-DCHERIBSD_THREAD_TESTS
LIBADD+=	pthread
SRCS+=		cheriostest_tls_threads.c
.endif

.ifdef CHERIOSTEST_C18N_TESTS
CFLAGS+=	-DCHERIOSTEST_C18N_TESTS
ELF_FEATURES+=	+cheric18n
.endif

.include <bsd.prog.mk>
